In [1]:
import numpy as np

In [2]:
arr4 = np.zeros(10)
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
arr5 = np.ones(10)
print(arr4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
arr6 = np.ones(10)*10
print(arr6)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [8]:
arr7 = np.ones(10)*50
print(arr7)

[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [9]:
arr6 = np.ones(10)*5
print(arr6)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [10]:
arr6 = np.ones(10)*20
print(arr6)

[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
